# Generated by Django 5.0.6 on 2024-06-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_event_bandevent_delete_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bands',
        ),
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.ManyToManyField(to='eventsapp.bands'),
        ),
    ]
