# Generated by Django 5.0.6 on 2024-06-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStoreApp', '0003_alter_book_num_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('DR', 'Drama'), ('AC', 'Action'), ('TR', 'Thriler'), ('RM', 'Romance'), ('BI', 'Biography'), ('CK', 'Clasic')], default='CK', max_length=6),
        ),
    ]
